// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.security;

import org.easybi.security.SecurityUserDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SecurityUserDataOnDemand_Roo_Configurable {
    
    declare @type: SecurityUserDataOnDemand: @Configurable;
    
}
