// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.security;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.easybi.security.SecurityUser;
import org.easybi.security.SecurityUserDataOnDemand;
import org.easybi.security.SecurityUserIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SecurityUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SecurityUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SecurityUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SecurityUserIntegrationTest: @Transactional;
    
    @Autowired
    SecurityUserDataOnDemand SecurityUserIntegrationTest.dod;
    
    @Test
    public void SecurityUserIntegrationTest.testCountSecurityUsers() {
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", dod.getRandomSecurityUser());
        long count = SecurityUser.countSecurityUsers();
        Assert.assertTrue("Counter for 'SecurityUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SecurityUserIntegrationTest.testFindSecurityUser() {
        SecurityUser obj = dod.getRandomSecurityUser();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to provide an identifier", id);
        obj = SecurityUser.findSecurityUser(id);
        Assert.assertNotNull("Find method for 'SecurityUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SecurityUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SecurityUserIntegrationTest.testFindAllSecurityUsers() {
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", dod.getRandomSecurityUser());
        long count = SecurityUser.countSecurityUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'SecurityUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SecurityUser> result = SecurityUser.findAllSecurityUsers();
        Assert.assertNotNull("Find all method for 'SecurityUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SecurityUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SecurityUserIntegrationTest.testFindSecurityUserEntries() {
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", dod.getRandomSecurityUser());
        long count = SecurityUser.countSecurityUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SecurityUser> result = SecurityUser.findSecurityUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SecurityUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SecurityUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SecurityUserIntegrationTest.testFlush() {
        SecurityUser obj = dod.getRandomSecurityUser();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to provide an identifier", id);
        obj = SecurityUser.findSecurityUser(id);
        Assert.assertNotNull("Find method for 'SecurityUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySecurityUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SecurityUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SecurityUserIntegrationTest.testMergeUpdate() {
        SecurityUser obj = dod.getRandomSecurityUser();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to provide an identifier", id);
        obj = SecurityUser.findSecurityUser(id);
        boolean modified =  dod.modifySecurityUser(obj);
        Integer currentVersion = obj.getVersion();
        SecurityUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SecurityUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SecurityUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", dod.getRandomSecurityUser());
        SecurityUser obj = dod.getNewTransientSecurityUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SecurityUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SecurityUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SecurityUserIntegrationTest.testRemove() {
        SecurityUser obj = dod.getRandomSecurityUser();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SecurityUser' failed to provide an identifier", id);
        obj = SecurityUser.findSecurityUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SecurityUser' with identifier '" + id + "'", SecurityUser.findSecurityUser(id));
    }
    
}
