// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import org.easybi.model.Stat;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Stat_Roo_Configurable {
    
    declare @type: Stat: @Configurable;
    
}
