// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.security;

import org.easybi.security.SecurityUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SecurityUser_Roo_Configurable {
    
    declare @type: SecurityUser: @Configurable;
    
}
