// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.easybi.model.Flow;
import org.easybi.model.FlowDataOnDemand;
import org.easybi.model.FlowIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FlowIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FlowIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FlowIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FlowIntegrationTest: @Transactional;
    
    @Autowired
    FlowDataOnDemand FlowIntegrationTest.dod;
    
    @Test
    public void FlowIntegrationTest.testCountFlows() {
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", dod.getRandomFlow());
        long count = Flow.countFlows();
        Assert.assertTrue("Counter for 'Flow' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FlowIntegrationTest.testFindFlow() {
        Flow obj = dod.getRandomFlow();
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Flow' failed to provide an identifier", id);
        obj = Flow.findFlow(id);
        Assert.assertNotNull("Find method for 'Flow' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Flow' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FlowIntegrationTest.testFindAllFlows() {
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", dod.getRandomFlow());
        long count = Flow.countFlows();
        Assert.assertTrue("Too expensive to perform a find all test for 'Flow', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Flow> result = Flow.findAllFlows();
        Assert.assertNotNull("Find all method for 'Flow' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Flow' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FlowIntegrationTest.testFindFlowEntries() {
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", dod.getRandomFlow());
        long count = Flow.countFlows();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Flow> result = Flow.findFlowEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Flow' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Flow' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FlowIntegrationTest.testFlush() {
        Flow obj = dod.getRandomFlow();
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Flow' failed to provide an identifier", id);
        obj = Flow.findFlow(id);
        Assert.assertNotNull("Find method for 'Flow' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFlow(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Flow' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FlowIntegrationTest.testMergeUpdate() {
        Flow obj = dod.getRandomFlow();
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Flow' failed to provide an identifier", id);
        obj = Flow.findFlow(id);
        boolean modified =  dod.modifyFlow(obj);
        Integer currentVersion = obj.getVersion();
        Flow merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Flow' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FlowIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", dod.getRandomFlow());
        Flow obj = dod.getNewTransientFlow(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Flow' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Flow' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Flow' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FlowIntegrationTest.testRemove() {
        Flow obj = dod.getRandomFlow();
        Assert.assertNotNull("Data on demand for 'Flow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Flow' failed to provide an identifier", id);
        obj = Flow.findFlow(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Flow' with identifier '" + id + "'", Flow.findFlow(id));
    }
    
}
