// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.easybi.model.Flow;
import org.easybi.model.FlowDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect FlowDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FlowDataOnDemand: @Component;
    
    private Random FlowDataOnDemand.rnd = new SecureRandom();
    
    private List<Flow> FlowDataOnDemand.data;
    
    public Flow FlowDataOnDemand.getNewTransientFlow(int index) {
        Flow obj = new Flow();
        setContext(obj, index);
        setCount(obj, index);
        setFather_pid(obj, index);
        setJob(obj, index);
        setJob_repository_id(obj, index);
        setJob_version(obj, index);
        setLabel(obj, index);
        setMoment(obj, index);
        setOrigin(obj, index);
        setPid(obj, index);
        setProject(obj, index);
        setReference(obj, index);
        setRoot_pid(obj, index);
        setSystem_pid(obj, index);
        setThresholds(obj, index);
        return obj;
    }
    
    public void FlowDataOnDemand.setContext(Flow obj, int index) {
        String context = "context_" + index;
        if (context.length() > 50) {
            context = context.substring(0, 50);
        }
        obj.setContext(context);
    }
    
    public void FlowDataOnDemand.setCount(Flow obj, int index) {
        Integer count = new Integer(index);
        obj.setCount(count);
    }
    
    public void FlowDataOnDemand.setFather_pid(Flow obj, int index) {
        String father_pid = "father_pid_" + index;
        if (father_pid.length() > 20) {
            father_pid = father_pid.substring(0, 20);
        }
        obj.setFather_pid(father_pid);
    }
    
    public void FlowDataOnDemand.setJob(Flow obj, int index) {
        String job = "job_" + index;
        if (job.length() > 255) {
            job = job.substring(0, 255);
        }
        obj.setJob(job);
    }
    
    public void FlowDataOnDemand.setJob_repository_id(Flow obj, int index) {
        String job_repository_id = "job_repository_id_" + index;
        if (job_repository_id.length() > 255) {
            job_repository_id = job_repository_id.substring(0, 255);
        }
        obj.setJob_repository_id(job_repository_id);
    }
    
    public void FlowDataOnDemand.setJob_version(Flow obj, int index) {
        String job_version = "job_version_" + index;
        if (job_version.length() > 255) {
            job_version = job_version.substring(0, 255);
        }
        obj.setJob_version(job_version);
    }
    
    public void FlowDataOnDemand.setLabel(Flow obj, int index) {
        String label = "label_" + index;
        if (label.length() > 255) {
            label = label.substring(0, 255);
        }
        obj.setLabel(label);
    }
    
    public void FlowDataOnDemand.setMoment(Flow obj, int index) {
        Date moment = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setMoment(moment);
    }
    
    public void FlowDataOnDemand.setOrigin(Flow obj, int index) {
        String origin = "origin_" + index;
        if (origin.length() > 255) {
            origin = origin.substring(0, 255);
        }
        obj.setOrigin(origin);
    }
    
    public void FlowDataOnDemand.setPid(Flow obj, int index) {
        String pid = "pid_" + index;
        if (pid.length() > 20) {
            pid = pid.substring(0, 20);
        }
        obj.setPid(pid);
    }
    
    public void FlowDataOnDemand.setProject(Flow obj, int index) {
        String project = "project_" + index;
        if (project.length() > 50) {
            project = project.substring(0, 50);
        }
        obj.setProject(project);
    }
    
    public void FlowDataOnDemand.setReference(Flow obj, int index) {
        Integer reference = new Integer(index);
        obj.setReference(reference);
    }
    
    public void FlowDataOnDemand.setRoot_pid(Flow obj, int index) {
        String root_pid = "root_pid_" + index;
        if (root_pid.length() > 20) {
            root_pid = root_pid.substring(0, 20);
        }
        obj.setRoot_pid(root_pid);
    }
    
    public void FlowDataOnDemand.setSystem_pid(Flow obj, int index) {
        BigInteger system_pid = BigInteger.valueOf(index);
        obj.setSystem_pid(system_pid);
    }
    
    public void FlowDataOnDemand.setThresholds(Flow obj, int index) {
        String thresholds = "thresholds_" + index;
        if (thresholds.length() > 255) {
            thresholds = thresholds.substring(0, 255);
        }
        obj.setThresholds(thresholds);
    }
    
    public Flow FlowDataOnDemand.getSpecificFlow(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Flow obj = data.get(index);
        Long id = obj.getId();
        return Flow.findFlow(id);
    }
    
    public Flow FlowDataOnDemand.getRandomFlow() {
        init();
        Flow obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Flow.findFlow(id);
    }
    
    public boolean FlowDataOnDemand.modifyFlow(Flow obj) {
        return false;
    }
    
    public void FlowDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Flow.findFlowEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Flow' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Flow>();
        for (int i = 0; i < 10; i++) {
            Flow obj = getNewTransientFlow(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
