// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import org.easybi.model.LogIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LogIntegrationTest_Roo_Configurable {
    
    declare @type: LogIntegrationTest: @Configurable;
    
}
