// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.easybi.model.Stat;
import org.easybi.model.StatDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect StatDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StatDataOnDemand: @Component;
    
    private Random StatDataOnDemand.rnd = new SecureRandom();
    
    private List<Stat> StatDataOnDemand.data;
    
    public Stat StatDataOnDemand.getNewTransientStat(int index) {
        Stat obj = new Stat();
        setContext(obj, index);
        setDuration(obj, index);
        setFather_pid(obj, index);
        setJob(obj, index);
        setJob_repository_id(obj, index);
        setJob_version(obj, index);
        setMessage(obj, index);
        setMessage_type(obj, index);
        setMoment(obj, index);
        setOrigin(obj, index);
        setPid(obj, index);
        setProject(obj, index);
        setRoot_pid(obj, index);
        setSystem_pid(obj, index);
        return obj;
    }
    
    public void StatDataOnDemand.setContext(Stat obj, int index) {
        String context = "context_" + index;
        if (context.length() > 50) {
            context = context.substring(0, 50);
        }
        obj.setContext(context);
    }
    
    public void StatDataOnDemand.setDuration(Stat obj, int index) {
        BigInteger duration = BigInteger.valueOf(index);
        obj.setDuration(duration);
    }
    
    public void StatDataOnDemand.setFather_pid(Stat obj, int index) {
        String father_pid = "father_pid_" + index;
        if (father_pid.length() > 20) {
            father_pid = father_pid.substring(0, 20);
        }
        obj.setFather_pid(father_pid);
    }
    
    public void StatDataOnDemand.setJob(Stat obj, int index) {
        String job = "job_" + index;
        if (job.length() > 255) {
            job = job.substring(0, 255);
        }
        obj.setJob(job);
    }
    
    public void StatDataOnDemand.setJob_repository_id(Stat obj, int index) {
        String job_repository_id = "job_repository_id_" + index;
        if (job_repository_id.length() > 255) {
            job_repository_id = job_repository_id.substring(0, 255);
        }
        obj.setJob_repository_id(job_repository_id);
    }
    
    public void StatDataOnDemand.setJob_version(Stat obj, int index) {
        String job_version = "job_version_" + index;
        if (job_version.length() > 255) {
            job_version = job_version.substring(0, 255);
        }
        obj.setJob_version(job_version);
    }
    
    public void StatDataOnDemand.setMessage(Stat obj, int index) {
        String message = "message_" + index;
        if (message.length() > 255) {
            message = message.substring(0, 255);
        }
        obj.setMessage(message);
    }
    
    public void StatDataOnDemand.setMessage_type(Stat obj, int index) {
        String message_type = "message_type_" + index;
        if (message_type.length() > 255) {
            message_type = message_type.substring(0, 255);
        }
        obj.setMessage_type(message_type);
    }
    
    public void StatDataOnDemand.setMoment(Stat obj, int index) {
        Date moment = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setMoment(moment);
    }
    
    public void StatDataOnDemand.setOrigin(Stat obj, int index) {
        String origin = "origin_" + index;
        if (origin.length() > 255) {
            origin = origin.substring(0, 255);
        }
        obj.setOrigin(origin);
    }
    
    public void StatDataOnDemand.setPid(Stat obj, int index) {
        String pid = "pid_" + index;
        if (pid.length() > 20) {
            pid = pid.substring(0, 20);
        }
        obj.setPid(pid);
    }
    
    public void StatDataOnDemand.setProject(Stat obj, int index) {
        String project = "project_" + index;
        if (project.length() > 50) {
            project = project.substring(0, 50);
        }
        obj.setProject(project);
    }
    
    public void StatDataOnDemand.setRoot_pid(Stat obj, int index) {
        String root_pid = "root_pid_" + index;
        if (root_pid.length() > 20) {
            root_pid = root_pid.substring(0, 20);
        }
        obj.setRoot_pid(root_pid);
    }
    
    public void StatDataOnDemand.setSystem_pid(Stat obj, int index) {
        BigInteger system_pid = BigInteger.valueOf(index);
        obj.setSystem_pid(system_pid);
    }
    
    public Stat StatDataOnDemand.getSpecificStat(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Stat obj = data.get(index);
        Long id = obj.getId();
        return Stat.findStat(id);
    }
    
    public Stat StatDataOnDemand.getRandomStat() {
        init();
        Stat obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Stat.findStat(id);
    }
    
    public boolean StatDataOnDemand.modifyStat(Stat obj) {
        return false;
    }
    
    public void StatDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Stat.findStatEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Stat' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Stat>();
        for (int i = 0; i < 10; i++) {
            Stat obj = getNewTransientStat(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
