// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.easybi.model.Stat;
import org.easybi.model.StatDataOnDemand;
import org.easybi.model.StatIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StatIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StatIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StatIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StatIntegrationTest: @Transactional;
    
    @Autowired
    StatDataOnDemand StatIntegrationTest.dod;
    
    @Test
    public void StatIntegrationTest.testCountStats() {
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", dod.getRandomStat());
        long count = Stat.countStats();
        Assert.assertTrue("Counter for 'Stat' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StatIntegrationTest.testFindStat() {
        Stat obj = dod.getRandomStat();
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stat' failed to provide an identifier", id);
        obj = Stat.findStat(id);
        Assert.assertNotNull("Find method for 'Stat' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Stat' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StatIntegrationTest.testFindAllStats() {
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", dod.getRandomStat());
        long count = Stat.countStats();
        Assert.assertTrue("Too expensive to perform a find all test for 'Stat', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Stat> result = Stat.findAllStats();
        Assert.assertNotNull("Find all method for 'Stat' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Stat' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StatIntegrationTest.testFindStatEntries() {
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", dod.getRandomStat());
        long count = Stat.countStats();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Stat> result = Stat.findStatEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Stat' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Stat' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StatIntegrationTest.testFlush() {
        Stat obj = dod.getRandomStat();
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stat' failed to provide an identifier", id);
        obj = Stat.findStat(id);
        Assert.assertNotNull("Find method for 'Stat' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStat(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Stat' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatIntegrationTest.testMergeUpdate() {
        Stat obj = dod.getRandomStat();
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stat' failed to provide an identifier", id);
        obj = Stat.findStat(id);
        boolean modified =  dod.modifyStat(obj);
        Integer currentVersion = obj.getVersion();
        Stat merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Stat' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", dod.getRandomStat());
        Stat obj = dod.getNewTransientStat(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Stat' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Stat' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Stat' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StatIntegrationTest.testRemove() {
        Stat obj = dod.getRandomStat();
        Assert.assertNotNull("Data on demand for 'Stat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stat' failed to provide an identifier", id);
        obj = Stat.findStat(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Stat' with identifier '" + id + "'", Stat.findStat(id));
    }
    
}
